### ISSUE TITLE
conda-forge recipe request

### ISSUE THREAD

**Issue by owenlamont** [JackMcKew/pandas_alive#12] opened 2020-08-29 12:45 UTC
I wanted to request creating a conda-forge recipe for pandas_alive (given I'd love to use it and I almost exclusively use conda  and don't touch PyPi much...)

The advantage to other developers would be we could set ffmpeg and imagemagick as dependencies to be automatically install too (conda-forge has an ffmpeg recipe for all major OSes and and imagemagick recipe for Linux/OSX - I'm trying to ask for a [Windows recipe for imagemagick](https://github.com/conda-forge/imagemagick-feedstock/issues/156) too) so it would make setting up a working environment for pandas_alive really easy. I'd be happy to help work on this if you're open to it.

Thanks again for the excellent package - I've made a lot of matplotlib animations with Pandas data sources and had thought about creating something similar a while back but this way surpasses what I had in mind.

**Comment by JackMcKew** [comment] 2020-08-29 23:50
Hi @owenlamont, thank you for raising this issue and it's a fantastic idea.

I've gone to the effort at putting together the staged-recipe for `pandas_alive` and submitted the PR which you can see <https://github.com/conda-forge/staged-recipes/pull/12508>.

Personally I still like the idea of choice from the developer to whether they are using Pillow, ffmpeg or imagemagick and making it deliberate, but Anaconda should at least help with making the installation step easier. However, I'm still unsure whether `pandas_alive` will automatically use the dependency when installed in an Anaconda environment, if you know (or could look into this), that would be greatly appreciated to streamline user experience.

Thank you very much! I'm glad `pandas_alive` helped you in one way or another, that was my goal 😄

**Comment by JackMcKew** [comment] 2020-08-30 02:27
@owenlamont The PR for the comes forge recipe has been merged! 😃

**Comment by owenlamont** [comment] 2020-08-30 14:45
Awesome! I’ll try the conda recipe tomorrow. I’ve been mentioning it to my co-workers and local data science meetup already. I guess you can close this ticket.

If you ever want any help looking after the conda recipe feel free to add me as a maintainer in the recipe.

**Comment by JackMcKew** [comment] 2020-08-30 22:21
Awesome!

You've now been added as a maintainer of the `pandas-alive` feedstock, it would be greatly appreciated if you could lead the cause from here on!

**Closed by JackMcKew** 2020-08-30 22:21 UTC
Labels: enhancement

**Comment by owenlamont** [comment] 2020-08-31 14:36
No problem, I'll keep an eye on the conda recipe.
